### PR TITLE
Add Validation Test

### PR DESCRIPTION
**Pull request by DyrellC**
This PR contains a test to determine if the `DONT_VALIDATE_TESTNET_MILESTONE_SIG` configuration is operating as intended. The default value for this flag should be `false`.

To test this, a db containing a mix of milestones was created. There are a number of milestones generated using the expected, signed address seed, while there are others that were added using a different seed. Two nodes are spun up, one with the default configuration for validation, and one with the flag set to `true`. 

The node using the default configuration will only solidify the milestones up to a certain point, as it will only validate milestones issued using the proper address for signatures. The other node will solidify the additional milestones because it will not be looking for a validated signature.

### CODE REVIEW

**Comment by GalRogozinski** [comment]
> while there are others that were added using a different address

It should be the same address but with a bad sig

**Comment by GalRogozinski** [comment]
@DyrellC did you add the script?
If so, can you put a link?

**Comment by DyrellC** [comment]
@GalRogozinski  No I had not, sorry. @alon-e  When you say add the script, do you mean the script used to generate the db? I used several scripts for this if that is the case. I could do a comment  on how the db was generated as well as why the test should work in the feature description if that seems appropriate.

**Comment by DyrellC** [comment]
@GalRogozinski  No I had not, sorry. @alon-e  When you say add the script, do you mean the script used to generate the db? I used several scripts for this if that is the case. I could do a comment  on how the db was generated as well as why the test should work in the feature description if that seems appropriate.

**Pull request merged**
